export enum TRANSACTION_TYPES {
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  PURCHASE = "PURCHASE",
  INVESTMENT = "INVESTMENT",
  RETURN = "RETURN",
}

export enum COLOR {
  SUCCESS = "16A34A",
  ERROR = "DC2626",
}
