export enum TRANSACTION_TYPES {
  DEPOSIT = "DEPOSIT",
  WITHDRAWAL = "WITHDRAWAL",
  PURCHASE = "PURCHASE",
  INVESTMENT = "INVESTMENT",
  RETURN = "RETURN",
}

export enum COLOR {
  SUCCESS = "16A34A",
  ERROR = "DC2626",
}

export enum ROUNDING_TYPES {
  NEAREST_500 = "NEAREST_500",
  NEAREST_1000 = "NEAREST_1000",
  NEAREST_5000 = "NEAREST_5000",
  FIXED_AMOUNT = "FIXED_AMOUNT",
}

export enum RISK_PROFILES {
  CONSERVATIVE = "CONSERVATIVE",
  MODERATE = "MODERATE",
  AGGRESSIVE = "AGGRESSIVE",
}
